export const PERGUNTAS: Record<number, string[]> = {
  1: [ // NR-1 Psicossocial
    'Sinto que meu trabalho tem significado e propósito.',
    'Tenho autonomia para tomar decisões no meu trabalho.',
    'Me sinto psicologicamente seguro para expressar opiniões.',
    'Minha carga de trabalho é gerenciável e equilibrada.',
    'Tenho tempo suficiente para concluir minhas tarefas com qualidade.',
    'Raramente preciso trabalhar além do horário para cumprir demandas.',
    'Meu gestor imediato é respeitoso e justo comigo.',
    'Recebo orientações claras sobre o que se espera de mim.',
    'Sinto que minha liderança se preocupa com meu bem-estar.',
    'As informações importantes chegam a mim de forma clara e oportuna.',
    'Me sinto à vontade para comunicar problemas à liderança.',
    'Existe boa comunicação entre as equipes da empresa.',
    'Tenho bom relacionamento com meus colegas de trabalho.',
    'O ambiente de trabalho é colaborativo e respeitoso.',
    'Conflitos são resolvidos de forma saudável na equipe.',
    'Me sinto bem fisicamente para realizar meu trabalho.',
    'Consigo equilibrar vida pessoal e profissional.',
    'A empresa oferece suporte para minha saúde e bem-estar.',
    'Raramente sinto sintomas de estresse excessivo por conta do trabalho.',
    'Me sinto reconhecido pelo esforço que dedico ao trabalho.',
  ],
  2: [ // Clima Organizacional
    'Estou satisfeito com meu trabalho de forma geral.',
    'Me sinto valorizado pela empresa.',
    'Recomendaria esta empresa como um bom lugar para trabalhar.',
    'Tenho orgulho de fazer parte desta organização.',
    'Meu gestor me apoia no desenvolvimento profissional.',
    'Recebo feedback construtivo com regularidade.',
    'A liderança inspira e motiva a equipe.',
    'As informações são compartilhadas de forma transparente.',
    'Tenho acesso às informações necessárias para realizar meu trabalho.',
    'Me sinto à vontade para dar sugestões e ideias.',
    'Meu esforço e resultados são reconhecidos.',
    'Existe um sistema justo de recompensas e benefícios.',
    'As oportunidades de crescimento são claras e acessíveis.',
    'Me sinto engajado e motivado no dia a dia.',
    'Tenho clareza sobre meus objetivos e metas.',
    'A empresa investe no meu desenvolvimento.',
    'Sinto que tenho futuro e crescimento nesta empresa.',
    'O ambiente me permite dar o meu melhor.',
    'Existe senso de propósito compartilhado na equipe.',
    'Estou comprometido com os resultados da empresa.',
  ],
  3: [ // Cultura Organizacional
    'Os valores da empresa são claros e praticados no dia a dia.',
    'Existe coerência entre o que a empresa fala e o que pratica.',
    'A diversidade e inclusão são respeitadas na organização.',
    'A ética é uma prioridade real na empresa.',
    'As decisões são tomadas de forma justa e transparente.',
    'Existe incentivo à inovação e novas ideias.',
    'Erros são tratados como oportunidades de aprendizado.',
    'A empresa tem uma cultura de colaboração e não de competição interna.',
    'Me identifico com a missão e visão da empresa.',
    'A cultura da empresa me permite ser autêntico no trabalho.',
    'Existe respeito pelas diferenças de opinião.',
    'A empresa promove um ambiente de segurança psicológica.',
    'Os rituais e práticas da empresa fortalecem o senso de pertencimento.',
    'A liderança serve de exemplo dos valores organizacionais.',
    'Existe equilíbrio entre resultados e bem-estar das pessoas.',
    'A cultura incentiva o crescimento contínuo.',
    'As regras e processos fazem sentido e são aplicados igualmente.',
    'Me sinto parte de algo maior do que minhas funções diárias.',
    'A empresa celebra conquistas e reconhece contribuições.',
    'Eu acredito no futuro e na direção que a empresa está tomando.',
  ],
  4: [ // DISC Comportamental
    'Gosto de assumir o controle e liderar situações desafiadoras.',
    'Tomo decisões com rapidez mesmo sob pressão.',
    'Prefiro resultados concretos a longas discussões.',
    'Encaro conflitos de frente quando necessário.',
    'Sou uma pessoa comunicativa e entusiasmada.',
    'Gosto de trabalhar em equipe e interagir com pessoas.',
    'Me motivo facilmente e motivo as pessoas ao meu redor.',
    'Prefiro ambientes dinâmicos e cheios de novidades.',
    'Valorizo a harmonia e o bom relacionamento no trabalho.',
    'Sou paciente e prefiro um ritmo constante de trabalho.',
    'Dou suporte e apoio emocional às pessoas da equipe.',
    'Prefiro evitar conflitos e buscar consenso.',
    'Sou detalhista e gosto de seguir processos e regras.',
    'Analiso bem antes de tomar decisões.',
    'Prefiro dados e fatos a opiniões subjetivas.',
    'Me preocupo com qualidade e precisão nas entregas.',
    'Me adapto bem a diferentes situações e perfis.',
    'Tenho facilidade para equilibrar foco em pessoas e em resultados.',
    'Consigo liderar tanto com firmeza quanto com empatia.',
    'Me reconheço como uma pessoa com perfil versátil no trabalho.',
  ],
  5: [ // Essencial Agro
    'O ambiente de trabalho no campo é seguro e adequado.',
    'Tenho os equipamentos e ferramentas necessários para meu trabalho.',
    'Me sinto respeitado pela liderança da propriedade/empresa.',
    'As condições climáticas e de trabalho são consideradas pela gestão.',
    'Tenho clareza sobre minhas funções e responsabilidades.',
    'A comunicação entre a equipe rural é eficaz.',
    'Recebo as orientações necessárias para executar o trabalho com qualidade.',
    'Existe preocupação real com a saúde e segurança da equipe.',
    'Me sinto valorizado pelo trabalho que realizo no campo.',
    'Tenho acesso a treinamentos e capacitações relevantes.',
    'A liderança considera minhas sugestões e experiências.',
    'O ritmo e a carga de trabalho são compatíveis com minhas capacidades.',
    'Sinto que meu trabalho contribui para os resultados da propriedade.',
    'Existe espírito de equipe e cooperação entre os colegas.',
    'Me sinto motivado para trabalhar nesta propriedade/empresa.',
    'As condições de moradia e alimentação (quando aplicável) são adequadas.',
    'Sinto orgulho de trabalhar no agronegócio.',
    'Existe uma cultura de respeito ao meio ambiente na empresa.',
    'Me sinto psicologicamente bem para exercer minhas funções.',
    'Acredito que tenho futuro e crescimento nesta empresa do agro.',
  ],
}

export const FORM_NOMES: Record<number, string> = {
  1: 'Mapeamento Psicossocial NR-1',
  2: 'Clima Organizacional',
  3: 'Cultura Organizacional',
  4: 'DISC Comportamental',
  5: 'Essencial Agro',
}
